TemplightTracer.cpp
Sometimes in the middle of profiling the condition in the removed ifs became true, and the timestamp values became inconsistent. (See #20)
Fixes #20
=> Fix inconsistency with timestamps

TemplightAction.cpp, TemplightAction.h
When -code-complete-at is used, the TemplightAction creates the
CodeCompletionConsumer object (because of creating the Sema) and
a FrontendAction TemplightAction wraps also tries to create the
CodeCompletionConsumer object. Clang breaks when the
CodeCompletionConsumer is created twice.
There is no way to tell the wrapped FrontendAction not to try to
(re)create the CodeCompletionConsumer. Because of this, the
templight executable does not support -code-completion-at.
This patch makes TemplightAction not to create the Sema (and the
CodeCompletionConsumer) unless the Templight functionality is asked
for. This way one can use -code-complete-at with the templight binary.
This fix is a workaround to make -code-complete-at work without
changing code in the Clang libraries.
=> Create Sema lazily to support -code-complete-at.

TemplightTracer.cpp, lib/TemplightExtraWriters.cpp, templight_clang_patch.diff, templight_driver.cpp
Most of the changes are fairly straightforward, but things got a little hairy because of the removal of `llvm::sys::TimeValue` in this commit: llvm-mirror/llvm@2864c2ae. Please have a look at the updated uses of `GetTimeUsage` in TemplightTracer.cpp.
=> get templight compiling again with clang trunk

PrintableTemplightEntries.h, README.md, TemplightAction.cpp, TemplightAction.h, TemplightDebugger.cpp, TemplightDebugger.h, TemplightProtobufWriter.cpp, TemplightTracer.cpp, TemplightTracer.h, lib/TemplightExtraWriters.cpp, lib/TemplightProtobufReader.cpp, templight_clang_patch.diff, templight_messages.proto
- Updates the patch file to work with clang trunk
- Removes custom ActiveTemplateInst and uses the new
CodeSynthesisContext class
- Adds the `add_subdirectory(templight)` to the cmake to reduce manual
steps required to build
- Updates README.md to reflect cmake subdirectory change
- The tests don't pass but it appears they weren't passing before
either
=> Update to more recent version of clang

templight_clang_patch.diff
Note that 'DeclaringSpecialMember' and 'DefiningSynthesizedFunction'
types are still not handled, because I believe they can't be printed out
without modifying clang's code further. Will need to take a deeper look
into that.
Clang SVN: https://llvm.org/svn/llvm-project/cfe/trunk@305745,
Clang git: de5743d6575952920b5938b9ed7269cd20f5bc23
=> Added new tests for each CodeSynthesisContext::Kind.

TemplightDebugger.cpp
Without this, the llvm::outs() output is buffered, and does not show, which makes the debugger look like it's not doing anything or hung (at least on Windows).
=> Force flush of output before reading input during debugging

templight_clang_patch.diff, templight_clang_patch_with_context.diff
I also tried crashing clang by adding `-templight-dump` into the Sema tests just as Gábor Horváth suggested. Nothing broke! :)
=> Some more fixes Gábor Horváth commented on

templight_clang_patch.diff, templight_clang_patch_with_context.diff, utils/create_patch.sh
Note that `utils/create_patch.sh` now uses `git` instead of `svn`.
LLVM git: 930bcc9bdfb9542a292c3de874d7e6ba1464cfe0
LLVM svn: https://llvm.org/svn/llvm-project/llvm/trunk@325569
clang git: 6eb4766e65557933c30152738c47e6ff34a1d216
clang svn: https://llvm.org/svn/llvm-project/cfe/trunk@325571
=> Added a templight-profile tag for timestamps

templight_driver.cpp
`llvm::sys::Process::GetArgumentVector` seems to be removed.
=> Fix argument parsing

CMakeLists.txt
With the following cmake command, I got a lot of "undefined symbol" linker errors:
```bash
cmake -G "Ninja" \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DLLVM_ENABLE_ASSERTIONS=ON \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \
-DLLVM_USE_LINKER=lld \
-DLLVM_TARGETS_TO_BUILD=X86 \
../llvm/
```
This patch adds the necessary libraries to `target_link_libraries`. Did anyone have similar issues when using ninja?
=> Fixed linker errors when building with ninja

CMakeLists.txt, TemplightProtobufWriter.cpp
Title says it all.
Link error:
```
ld.lld: error: undefined symbol: clang::PCHContainerOperations::PCHContainerOperations()
>>> referenced by new_allocator.h:120 (/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:120)
>>>               tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o:(main)
ld.lld: error: undefined symbol: clang::PCHContainerOperations::PCHContainerOperations()
>>> referenced by new_allocator.h:120 (/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:120)
>>>               tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o:(main)
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```
The warning:
``` …
```
=> Fixed a linking error and a warning

CMakeLists.txt, lib/TemplightAction.cpp, test/CMakeLists.txt, test/Unit/lit.cfg.py, test/Unit/lit.site.cfg.py.in, test/lit.cfg, test/lit.site.cfg.in, test/templight-driver-flag.cpp, unittests/CMakeLists.txt, unittests/TemplightActionTest.cpp
The two new directories, `test/` and `unittests/` houses LLVM-like
regression and unit tests, both of which can be run under the new cmake
target check-templight.
You can test the entire templight project with the check-templight and check-clang-templight targets, as the latter checks the test files within clang.
What I'll do going forward:
```
ninja -C ../build check-templight check-clang-templight
```
Please, if you could, test this out before merging. llvm-lit likes to break on random platforms for random reasons, and I don't have the resources to check them all.
=> Added lit and unit test infrastructure

.clang-format, include/PrintableTemplightEntries.h, include/TemplightAction.h, include/TemplightDebugger.h, include/TemplightEntryPrinter.h, include/TemplightProtobufWriter.h, include/TemplightTracer.h, include/ThinProtobuf.h, lib/TemplightAction.cpp, lib/TemplightDebugger.cpp, lib/TemplightEntryPrinter.cpp, lib/TemplightProtobufWriter.cpp, lib/TemplightTracer.cpp, templight_driver.cpp, utils/ExtraWriters/TemplightExtraWriters.cpp, utils/ExtraWriters/TemplightExtraWriters.h, utils/ProtobufReader/TemplightProtobufReader.cpp, utils/ProtobufReader/TemplightProtobufReader.h, utils/format.sh
```bash
$ clang-format --version
clang-format version 7.0.1 (tags/RELEASE_701/final)
$ clang-format -i $(find -type f -name "*.cpp")
$ clang-format -i $(find -type f -name "*.h")
```
I also tinkered with the top of the files in order not to introduce a newline there.
=> Applied clang-format

templight_driver.cpp
Upstream LLVM introduced an overload with 5 arguments and added a 6th argument to the existing version.
=> Use the correct OptTable::PrintHelp()

lib/TemplightAction.cpp, lib/TemplightDebugger.cpp, lib/TemplightTracer.cpp, templight_driver.cpp
Trying to build templight against current clang trunk, I encountered a handful of errors.
Mostly just StringRef -> std::string conversions that needed to be made explicit.
=> fix clang trunk changes

README.md, lib/TemplightDebugger.cpp, lib/TemplightEntryPrinter.cpp, templight_driver.cpp, unittests/TemplightActionTest.cpp
Rebase on top of this commit in the llvm monorepo:
```
commit 8cc2de667ec2526b055e971f46f4b3731107546c
Author: Kristóf Umann <dkszelethus@gmail.com>
Date:   Mon Nov 8 14:40:45 2021 +0100
[analyzer][docs] Fix the incorrect structure of the checker docs
The alpha.security.cert section came right after alpha.security, making it look
like checkers like alpha.security.MmapWriteExec belonged to that package.
Differential Revision: https://reviews.llvm.org/D113397
```
=> Rebase on the current trunk

CMakeLists.txt, lib/TemplightProtobufWriter.cpp, templight_driver.cpp
This commit is just taking the #90 and updating some more things in the driver code to match up a bit more with the current state of the driver.cpp.
Tested manually, works fine now. But the check-templight still fails, it probably has to do with the old-style handling of cc1 mode.
=> Clang 15 compile fix

lib/TemplightProtobufWriter.cpp, templight_driver.cpp
...though I haven't checked whether the fix is correct, and check-templight doesn't work due to:
llvm-lit: /home/eumakri/Documents/llvm-project/llvm/utils/lit/lit/llvm/config.py:321: fatal: Could not turn '' into Itanium ABI triple
So this is little more than some progress on this issue.
=> [WIP] Fix compilation errors for Clang 15

include/ThinProtobuf.h
Hi
Looks like  #93 missed a few `endianness` namespace fixes.
Thanks!
=> More endianness namespace fixes.

templight_driver.cpp
While testing out templight, I noticed a small inconsistency compared to the regular `clang` driver: if there are no commands to run (e.g. because the specified source file doesn't exist), `templight` returns an exit status of 0:
```sh
$ clang foo.cpp; echo exit status was $?
clang: error: no such file or directory: 'foo.cpp'
clang: error: no input files
exit status was 1
$ ./bin/templight foo.cpp; echo exit status was $?
templight-16: error: no such file or directory: 'foo.cpp'
templight-16: error: no input files
exit status was 0
```
Note that I changed the initial value of `Res` to be 1 so that `templight` will return a failing exit status unless the code can affirmatively state that the work succeeded. Looking over the `main` implementation, I think this change should be equivalent …
=> Return a non-zero exit status if there are no commands to run

templight_driver.cpp
Sorry about the noise. After thinking about my reasoning, I realized my implementation in #96 didn't make sense: there are perfectly-valid cases where the compiler should have no commands to run, like `templight --help` or `templight --version`.
This implementation should fix that by checking whether the driver's diagnostics have logged an error. This is what `clang` itself does, using `Driver::ExecuteCompilation`: https://github.com/llvm/llvm-project/blob/357bd61744bb8cc2b9b07447294fa977e5758550/clang/lib/Driver/Driver.cpp#L1935-L1937
Since templight doesn't call that member function, it needs to handle this condition in `main`.
=> Handle invalid arguments to `templight` in a better way

lib/TemplightDebugger.cpp
Simply replace '|' with ':' to make code navigation more user-friendly.
Now in vscode, we can use ctrl+click to locate template definitions.
=> Improve code navigation for debugger
